### ISSUE TITLE
as a user I want to support getting labels from other wikibases than wikidata

### ISSUE THREAD

**Issue by dpriskorn** [dpriskorn/entityshape#15]
please comment if you have interest in this

**Comment by GreenReaper** [comment]
I have some interest in this. I run [a Wikibase.cloud instance](https://furry.wikibase.cloud) as a prototype for a full Wikibase install associated with [WikiFur](https://WikiFur.com). I already have [an EntitySchema](https://furry.wikibase.cloud/wiki/EntitySchema:E1) intended to validate [instances of conventions](https://furry.wikibase.cloud/wiki/Item:Q4) like [ConFuzzled](https://furry.wikibase.cloud/wiki/Item:Q1). Right now it can be validated using the simple ShEx validator but this is an awkward tool to use.

**Comment by dpriskorn** [comment]
I wondered if anyone would reach out when I updated the code yesterday.
You were fast!

**Comment by GreenReaper** [comment]
Perhaps there will be more interest after WikiDataCon if you go ahead with the session you proposed. Last time around there was a strong Wikibase track that was quite well-attended, although I don't know if that is such a focus this time around.

**Comment by dpriskorn** [comment]
I wondered if anyone would reach out when I updated the code yesterday.
You were fast!

**Comment by dpriskorn** [comment]
I added support for any Wikibase, see PR
